# Site Settings
title: Haven 4 BREAD
email: party4bread@gmail.com
description: Some text about your blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://party4bread.github.io" # the base hostname & protocol for your site
google_analytics: "UA-118293925-1"

# User Settings
username: Party4Bread
user_description: High Schooler, Interested in Crypto, Forensic, Reversing, .NET and Android
disqus_username: Party4Bread

# Social Media
# Remove the item if you don't need it
github_username: Party4Bread

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
