name: Haven 4 BREAD
title: Haven 4 BREAD | P4B's blog
description: Party4Bread's blog. Usally bloging about dev things.
tags:
  - blog
  - development
  - ctf
  - reversing
email: party4bread@gmail.com
disqus_username: party4bread
show_hero: true
# paginate: 12