name: Haven 4 BREAD
title: Haven 4 BREAD | P4B's blog
description: Party4Bread's blog. Usally bloging about dev things.
tags:
  - blog
  - development
  - ctf
  - reversing
  - crypto
  - cryptography
  - dev
show_hero: true
paginate: -1
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: party4bread@gmail.com
disqus_username: p4bblog
